import type { NextPage } from 'next';
import Head from 'next/head';
import { Auth } from '../components/generic/Auth/Auth';
import { useUser } from '../hooks/useUser';

const Home: NextPage = () => {
  const { user } = useUser();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Auth>Witaj świecie {user?.email}</Auth>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
