import type { NextPage } from 'next';
import Head from 'next/head';
import { MainLayout } from '../components/generic/MainLayout/MainLayout';

const Home: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </MainLayout>
  );
};

export default Home;
