import type { NextPage } from 'next';
import Head from 'next/head';
import { BudgetChart } from '../components/generic/BudgetChart/BudgetChart';
import { MainLayout } from '../components/generic/MainLayout/MainLayout';

const Home: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BudgetChart
        projects={[
          {
            color: 'blue',
            cost: 3000,
            id: '1',
            name: 'Wycieczka',
          },
          {
            color: 'yellow',
            cost: 2000,
            id: '1',
            name: 'Wycieczka',
          },
        ]}
      />
    </MainLayout>
  );
};

export default Home;
